# Generated by Django 3.2.5 on 2021-07-20 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_enrollment_date_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='date_enrolled',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
